package generator

import (
	"github.com/switchupcb/copygen/cli/models"
)

// Header creates the header of the generated file.
func Header(g *models.Generator) string {
	var header string

	// package
	header += "// Code generated by github.com/switchupcb/copygen\n"
	header += "// DO NOT EDIT.\n"
	header += "package " + g.Package + "\n"

	// imports
	header += "import (\n"
	for _, iprt := range g.Imports {
		header += "\"" + iprt + "\"\n"
	}
	header += ")"
	return header
}
