// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	"github.com/switchupcb/copygen/examples/_tests/cyclic/domain"
	"github.com/switchupcb/copygen/examples/_tests/cyclic/models"
)

// ModelsToDomain copies a Account, User to a Account.
func ModelsToDomain(tA *domain.Account, fA *models.Account, fU *models.User) {
	// Account fields
	tA.Info.Username = fA.Info.Username
	tA.Info.UserID = fA.Info.UserID
	tA.Name = fA.Name
	tA.ID = fA.ID

}
