// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package copygen

import (
	"github.com/switchupcb/copygen/example/converter"
	"github.com/switchupcb/copygen/example/domain"
	"github.com/switchupcb/copygen/example/models"
)

// ModelsToDomain copies fields from a models User and models Account to a domain Account.
func ModelsToDomain(tA *domain.Account, fU models.User, fA models.Account) error {
	tA.UserID = c.Itoa(fU.ID)
	tA.ID = fA.ID
	tA.Name = fA.Name
	return nil
}
