// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.
package copygen

import (
	"github.com/switchupcb/copygen/example/converter"
	"github.com/switchupcb/copygen/example/domain"
	"github.com/switchupcb/copygen/example/models"
)

// ModelsToDomain copies a User, Account to a Account.
func ModelsToDomain(tA *domain.Account, fU models.User, fA models.Account) {
	// Account fields
	tA.UserID = c.Itoa(tA.ID)
	tA.ID = fA.ID
	tA.Name = fA.Name

}
