// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	"github.com/switchupcb/copygen/examples/tag/domain"
	"github.com/switchupcb/copygen/examples/tag/models"
)

// ModelsToDomain copies a Account, User to a Account.
func ModelsToDomain(tA *domain.Account, fA *models.Account, fU *models.User) {
	// Account fields
	tA.ID = fU.UserID
	tA.Name = fA.Name
	tA.Username = fU.Username
}
