// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package convert

// NoConvertPlaceholder copies a Placeholder to a bool.
func NoConvertPlaceholder(tb bool, fP Placeholder) {
	// bool fields
}

// NoConvertBool copies a bool to a Placeholder.
func NoConvertBool(tP Placeholder, fb bool) {
	// Placeholder fields
}

// MapConvertPlaceholder copies a Placeholder to a bool.
func MapConvertPlaceholder(tb bool, fP Placeholder) {
	// bool fields
	tb = fP.(bool)
}

// MapConvertPlaceholderWithExpression copies a Placeholder to a int.
func MapConvertPlaceholderWithExpression(ti int, fP Placeholder) {
	// int fields
	ti = fP.(int) + 5
}
