run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - unused # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - deadcode # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - gomnd # Run manually prior to a release.
    - gomoddirectives # The repository uses go modules in its interpreter functionality from a temporary tagged fork.

    - lll
    - nlreturn
    - whitespace
    - wsl
    - forbidigo
    - gochecknoglobals # No data race conditions
    - gofumpt # too many false positives
    - exhaustivestruct # exhausting
    - exhaustruct
    - varnamelen # for loops
    - funlen # can't handle switch statement
    - nestif # can't handle cache
    - goerr113 # errors used once
    - cyclop 
    - gocognit


    - golint # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated

  fast: false
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      # - fieldalignment
  wrapcheck:
    ignorePackageGlobs:
      - github.com/switchupcb/copygen/cli/generator/*