run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - gomoddirectives # The repository uses go modules in its interpreter functionality from a temporary tagged fork.

    - cyclop
    - depguard
    - err113 # future implementation
    - exhaustruct
    - forbidigo
    - funlen # can't handle switch statement
    - gochecknoglobals # No data race conditions
    - gocognit
    - gofumpt # too many false positives
    - intrange
    - lll
    - mnd
    - nestif # can't handle cache
    - nlreturn
    - unparam # generator function
    - varnamelen # for loops
    - whitespace
    - wsl

    - tenv # deprecated


  fast: false
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      # - fieldalignment
  wrapcheck:
    ignorePackageGlobs:
      - github.com/switchupcb/copygen/cli/generator/*
  revive:
    rules:
      - name: unused-parameter
        disabled: true
