run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - gomnd # Run manually prior to a release.
    - gomoddirectives # The repository uses go modules in its interpreter functionality from a temporary tagged fork.

    - cyclop 
    - exhaustruct
    - exhaustivestruct # exhausting
    - forbidigo
    - funlen # can't handle switch statement
    - gochecknoglobals # No data race conditions
    - gocognit
    - goerr113 # errors used once
    - gofumpt # too many false positives
    - lll
    - nestif # can't handle cache
    - nlreturn
    - unparam # generator function
    - varnamelen # for loops
    - whitespace
    - wsl

    - deadcode # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated

  fast: false
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      # - fieldalignment
  wrapcheck:
    ignorePackageGlobs:
      - github.com/switchupcb/copygen/cli/generator/*
  revive:
    rules:
      - name: unused-parameter
        disabled: true
