// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package copygen

import (
	domain "github.com/switchupcb/copygen/examples/main/domain"
	models "github.com/switchupcb/copygen/examples/main/models"
	c "strconv"
)

// ModelsToDomain copies a Account, User to a Account.
func ModelsToDomain(tA *domain.Account, fA models.Account, fU models.User) {
	// Account fields
	tA.ID = fA.ID
	tA.UserID = fU.UserID
	tA.Name = fA.Name

}
