// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	"github.com/switchupcb/copygen/examples/tests/tag/domain"
	"github.com/switchupcb/copygen/examples/tests/tag/models"
)

// ModelsToDomain copies a Account, User to a Account.
func ModelsToDomain(tA *domain.Account, fA models.Account, fU models.User) {
	// Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
	tA.User.UserID = fU.UserID
	tA.User.Username = fU.Username
	tA.Email = fA.Email
	tA.Balance = fA.Bal
}
