// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	c "strconv"

	"github.com/switchupcb/copygen/examples/map/domain"
	"github.com/switchupcb/copygen/examples/map/models"
)

func Itoa(i int) string {
	return c.Itoa(i)
}

// ModelsToDomain copies a Account, User to a Account.
func ModelsToDomain(tA *domain.Account, fA *models.Account, fU *models.User) {
	// Account fields
	tA.ID = Itoa(fU.UserID)
	tA.Name = fA.Name
	tA.Email = fA.Email
}
